### ISSUE TITLE
Too much secondary information, consider two stage release 

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#103]
Tester comment:

Consider releasing the MDdb for beta testers in two-step process: a first step when only with “Minimal viable product MVP” is realized, showing only the more common parameters for MST deposit. 

This would allow us to focus the feedback on the important things and, more importantly, make the tester´s life easy and decrease the “learning curve” for the user. For instance,  secondary (and more confusing) information for MST as Pressure, Humidity or Funding reference would not be available in the first release. I am bit worry that people (even “early-adopters”) will not use the database because it is too complicated to use.

**Comment by JanDohnalek** [comment]
A lot can be achieved here by "hiding" optional input, especially in the context of the particular method.
I.e. more of a method-specific form.

**Comment by edager** [comment]
The schema/backend of this will be addressed in schema version 0.9.17
