### ISSUE TITLE
Change text for marking section as not provided 

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#104]
Some fields contain the text “do not provide this data” which could be confusing to the user because it seems more like an order to the user than a statement from the user. It may be something more friendly like “ I don’t want to provide this data”.

**Comment by JanDohnalek** [comment]
Agree, change needed.

**Comment by edager** [comment]
The logic of this will be inverted in the future. Instead of specifying that something isn't provided, one will have to add optional elements
