### ISSUE TITLE
Redundant “Do not provide this data” in  “Associated Publications”

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#105]
Tester comment:
In section “Associated Publications”  there are two “Do not provide this data”. I think one of them is unnecessary.

**Comment by JanDohnalek** [comment]
Many changes will happen - but we should have this in mind for some items.

**Comment by edager** [comment]
This section will be simplified, so this should no longer be an issue as  of general parameters version 0.9.17
