### ISSUE TITLE
Use the standard (*) instead of (■) for mandatory fields

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#106]
We consider it more intuitive to use (*) instead of (■) for the mandatory fields because it is what is usually used in other websites.

**Comment by JanDohnalek** [comment]
I agree.

**Comment by edager** [comment]
A somewhat different route  is taken by having the optional fields collapsed at the beginning. Is * still needed?

**Comment by edager** [comment]
I'm closing this at it is not present in the current input form
