### ISSUE TITLE
Person identifiers should be renamed to ORCID

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#109]
When we talk about ‘Identifiers’ of ‘Depositors’, ‘Principal Contact’ or other people, it is only available for ORCID numbers. So we should change ‘Identifier’ to ‘ORCID number’ to make the entry clearer.

**Comment by JanDohnalek** [comment]
This make it difficult to add new ids in the future so we will not keep change it.
