### ISSUE TITLE
More information about published work

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#111]
There is a ‘Publisher’ field which refers to editorial or journal but there is no option to include volume, issue, page, etc. Maybe this is too much information that we could collect from the DOI or a ‘cite’ option in the APA format in order to make the data entry more user-friendly.

**Comment by JanDohnalek** [comment]
There are other type of publications not just articles and there we need these fields as we can't pull it. We might have to explain this in the help text.

**Comment by edager** [comment]
In order to make this more clear and allow for different publication type depended information, publication will be turned into a polymorphic object as of general parameters 0.9.17 thereby solving this issue as we currently wont implement extraction of information from all types of journals.
