### ISSUE TITLE
Unclear what "Physical conditions at sample handling" refers to

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#112]
The explanation of the section “Physical conditions at sample handling” claims that it refers to the BEFORE handling. It is confusing and it is not clear the difference with the storage section.

**Comment by JanDohnalek** [comment]
The name will change to physical conditions prior to measurement

**Comment by edager** [comment]
This will appear in general parameters schema version 0.9.16
