### ISSUE TITLE
"Performance test" takes to much attention

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#113]
In the ‘Instrument’ section there is too much information about ‘Performance test’ which contributes to loss the focus. As an example of our confusion, we thought the “File” at the bottom of this section was the file with the raw data, but It was still related to the ‘performance test’.

**Comment by JanDohnalek** [comment]
see comment to  #114

**Comment by edager** [comment]
Performance test will be removed in general parameters 0.9.17 so this will close this issue
