### ISSUE TITLE
The input form is generally too complicated

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#116]
Generally speaking, it is very easy to get lost through the sections. Information with different levels of importance are presented at the same level in the interface and many times I don't know in which section and subsection I am

Reducing the fields or eliminating full sections should be considered.

Before eliminating fields  we could try playing with the colors of the levels of the db. Another option could be that the third level of information should be shown only when it is dropped down. For instance: “Published test protocol” which is inside “Performance test” which is inside of “Instrument” should not be fully displayed and its background should be in yellow (this is just an example).

**Comment by JanDohnalek** [comment]
There will be many changes ...

**Comment by edager** [comment]
The schema changes in order to address the schema part of this issue will be introduced in general parameters 0.9.17
