### ISSUE TITLE
Performance test could be another record in the MBDB

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#117]
Many times, the performance test will be just another record in the MDBD, that option should be given in the interface by giving the recordID of the performance test

**Comment by JanDohnalek** [comment]
Good point, we will consider how to implement it best.

**Comment by edager** [comment]
In order to simplify the schema performance test was removed, hence this well no longer be possible to use. This will take effect in schema version 0.9.17
