### ISSUE TITLE
‘Collection start time’  is oddly positioned 

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#118]
‘Collection start time’ field is in the middle of the deposit, which is a bit confusing, so we suggest including it in the ‘Raw measurements’ section because it is the date in which these measurements were taken. In addition, we think the field should not allow introducing dates after the current day.

**Comment by JanDohnalek** [comment]
fair point we will put it at the end. which is under the raw measurement
