### ISSUE TITLE
Ability to write the new experiment type when other is chosen 

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#121]
Related to method specific parameters, in the ‘Experiment type’ field, it is possible to choose between 3 options (Affinity, Concentration and Other). So, if we choose ‘Other’, a new field could appear to introduce by hand what kind of experiment is.

**Comment by JanDohnalek** [comment]
Currently we properly won't, as it makes it very difficult for long term data integrity. We might want include a field that allows to add information in case of other.
