### ISSUE TITLE
 ‘Excitation LED Power’ and ‘IR MST laser power’ per measurement instead of per experiment

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#123]
It could be a good idea to introduce the ‘Excitation LED Power’ and ‘IR MST laser power’ fields in each measurement because they can change between them within a record.

**Comment by JanDohnalek** [comment]
Further investigation needed.

**Comment by edager** [comment]
Investigated and in order for having records that are easier to reuse the schema will stay as is.
