### ISSUE TITLE
Why isn't the red icon disappearing 

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#126]
If all the mandatory fields in the Record information are completed, the red alert icon show disappear (?). I think it happens in other fields.
![image](https://github.com/Molecular-Biophysics-Database/mbdb-app/assets/20229814/f2a09fd5-c568-4bcb-a265-47c6ef3a8239)

**Comment by MadCatX** [comment]
As far as I can tell, this is correct behavior. `Project` belongs to the `Record information` section which is *not* marked as invalid. The warning is shown for the entire `General parameters` which appear to contain other invalid sections.

Perhaps it would be better to move the warning icon closer to the section title or draw the invalid sections in red font to reduce the possibility of confusion.
