### ISSUE TITLE
Context dependent option restrictions

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#135]
In the 'Unit' option, I was expecting to be able to choose from a list of units according to the selected derived parameter.

**Comment by JanDohnalek** [comment]
Will be partially implemented. Frontend vs. datamodel to be considered. High priority.

**Comment by edager** [comment]
datamodel-wise, this can be implemented by making derived_parameter polymorphic with respect to unit: https://github.com/Molecular-Biophysics-Database/mbdb-model/compare/development...polymorphic-params#diff-60b31f888ddf0073d88b02e0bcf3bb25442c1590651b360ee1b7e01045103691

**Comment by edager** [comment]
This will be introduced in general_parameters 0.9.17
