### ISSUE TITLE
Record view - Measurements - can we easily show the entities?

### ISSUE THREAD

**Issue by JanDohnalek** [Molecular-Biophysics-Database/mbdb-app#235]
For the particular measurement in the record view it would be useful to show which entitites were involved in the measurement.
If the user defines let's say three or more EOIs then the measurement information is there - defined by the user - which EOIs were measured in a particular measurement - I think this should be shown in the record view so that there is no doubt for example which interaction pair or may be combination of EOI1, EOI2 and EOI3 was actually measured.

**Comment by edager** [comment]
#229
