### ISSUE TITLE
Input form - EOI chemical causes "Internal error"

### ISSUE THREAD

**Issue by JanDohnalek** [Molecular-Biophysics-Database/mbdb-app#314]
Addition of EOI of type chemical saves OK until I add a particular chemical from vocabulary.
Then the Save produces 
"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

Interestingly, "water" from the local vocabulary saves OK.
5'-GMP from global **does not save -** produces the error above. (not in local vocabulary - checked)
Deuterium oxide - from global saves OK (???) and is added into the local vocab
Adenosine-5'-triphosphate from global saves OK and is added into local
Kirromycin from Streptomyces collinus produces again the Error when saving ...

**Comment by edager** [comment]
For 5'-GMP and Kirromycin from Streptomyces collinus  the problem was that multiple records existed for each of the molecules, only one of which had the full information including title.
