### ISSUE TITLE
Funding vocabulary - New item - produces database error

### ISSUE THREAD

**Issue by JanDohnalek** [Molecular-Biophysics-Database/mbdb-app#355]
Project information
Funding reference
Add item
- It lets me add item and then upon Save it produces error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

(When I call ..../vocabularies and add new funding reference in there, then I can return to the input form for the same record and add the newly created funding reference and it works fully through to submission and publication).

NOT CRITICAL but high priority

**Comment by edager** [comment]
This was fixed in #359 with version 2.1.1 of [oarepo-vocabularies](https://github.com/oarepo/oarepo-vocabularies)
