### ISSUE TITLE
Formalities in the record view

### ISSUE THREAD

**Issue by JanDohnalek** [Molecular-Biophysics-Database/mbdb-app#54]
Capitalize only the first letter
Entities of interest

The whole section for one Measurement should be graphically clearly belonging to the title (e.g. Measurement 1), This should be reflected by the font sizes etc... right now it looks as if Buffer and Constituents are new major categories but they actually belong to that one measurement ..

I find it misleading that the Instrument is at the top and then the actual experimental details are at the bottom.
I think the Instrument should live either above or below the Measurements block.

**Comment by edager** [comment]
This is three separate issues, please consider to raise it as such in the future as it  makes it easier to work with and mark as solved.
