### ISSUE TITLE
User Interface items

### ISSUE THREAD

**Issue by JanDohnalek** [Molecular-Biophysics-Database/mbdb-app#56]
Please add the "All entries" button at the top menu line before Documentation.
Moving into testing this should appear there..

**Comment by edager** [comment]
If you do an empty search, all entries will show, is that enough or is the button critical?

**Comment by JanDohnalek** [comment]
Not critical ... may be later.

**Comment by edager** [comment]
I'll close this now, however if the testers mention it I will reopen it.
