### ISSUE TITLE
Search behaviour - More meaningful link when no results are found

### ISSUE THREAD

**Issue by JanDohnalek** [Molecular-Biophysics-Database/mbdb-app#57]
When I did not find the search key and pressed start over - it put me to the complete listing instead of the search page.

**Comment by edager** [comment]
I'm not entirely sure what you mean, could you elaborate? Where/when couldn't you find the search key ? which start over button are you referring to ?

**Comment by JanDohnalek** [comment]
I mean the button Start over which appears under unsuccessful search. It takes you back to full listing instead of search field.

**Comment by edager** [comment]
The button in ui/mst/semantic-ui/js/mst/search/components/assets/semantic-ui/js/mbdb_mst_ui/search/components/EmptyResultsElement.jsx should point the frontpage rather than triggering a search with an empty query string

**Comment by edager** [comment]
This was fixed by #300
