### ISSUE TITLE
Depostion form - Save button difficult to reach

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#89]
Tester notes that:

It is possible to scroll down in the page so that you aren’t able to view the “Save” button at the top of the page, so you have to scroll all the way up to save, a bit annoying. Would be nicer if it is more easily accessed during the course of input, to ensure that people can do so regularly during the process.

**Comment by JanDohnalek** [comment]
Yes, will be implemented to have it available along the deposition form.
