### ISSUE TITLE
Deposition form - Default of collection start time is dangerous 

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#92]
Tester suggestion:

This doesn’t appear to be in any of the groups and doesn’t appear in the navigation tree either.

If you have the current date set as default, then chances are people are going to skip over it and therefore it won’t be accurate. Maybe better that no date is defined in a new entry, then force people to enter something before submission.

**Comment by MadCatX** [comment]
Suggestion: Make all default values of dates flagged as invalid. This will prevent deposition and force the user to set a value. See `src/schema/value.ts` `defaultForItem()` function in the input UI module.
