### ISSUE TITLE
Deposition form - Physical conditions at sample handling

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#93]
Tester question: 

![image](https://github.com/Molecular-Biophysics-Database/mbdb-app/assets/20229814/ae97f46d-f64e-4a08-a1a6-9fc21fde01e6)

Why is the field to add a (few?) digit number so large, and why can it accept so many characters?
After saving it turned the number into this…

![image](https://github.com/Molecular-Biophysics-Database/mbdb-app/assets/20229814/59df8962-c4e0-41af-bc4c-2ad87778b175)

**Comment by MadCatX** [comment]
Was there supposed to be a image attached to the issue? I cannot see what the problem is supposed to be.

**Comment by MadCatX** [comment]
I see the problem. Unfortunately, this is, technically, the correct behavior.

The input form does **not** make a distinction between textual and numeric input. Everything is stored as string internally. The reason for this is, partly, to avoid this exact issue. When a numeric value is expected, the form only checks if the currently inputted string represents a number.

It is only when we deposit that the string gets converted to a number and submitted. As a result, the exact representation of numbers is lost. When a record is restored from a draft, the `Number.toString()` function does the reasonable thing and displays the number in scientific notation (at least in the reported case).

There is no straightforward way how to resolve this. We could store numbers directly as strings but I wonder if the backend could be set to prevent deposition of "non-numerical" strings.

**Comment by edager** [comment]
It is indeed expected behaviour, as this is at least in principle a valid temperature(...), however I can see how  a tester might find it strange having something that visually would be recognised as a text field for imputing what would in 99 % of the cases be a 1-3 digit number.

**Comment by edager** [comment]
I'm closing this issue as the section that is being referred to no longer exists
