### ISSUE TITLE
Deposition form - Unrolled form and unclear indication of required fields

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#94]
Tester comment:

When looking at the navigation tree, it is telling me that there are some parameters/information missing in the Chemical information section, however when looking at the entry area, there are no red field or indications that something is missing

If chemical environments and entities of interest are required, then I think there should be as default all the fields being shown that are needed. Same goes for all the sub-group entries required in these sections.

**Comment by JanDohnalek** [comment]
This will be addressed by the overall redesign of data model and input form.
