### ISSUE TITLE
deposition form - unclear how to upload measured data

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#97]
Tester comment

Measured data
No information that I can see for how the data should be inputted

Is it true that you need to have a field per value you need to upload? 

Googling I see that MST output can look like this! So are you asking that each curve is entered point by point? I think I must be missing something….

**Comment by JanDohnalek** [comment]
Will be covered by the message connected with the upload window.

**Comment by edager** [comment]
This will be removed in MST 0.9.8
