### ISSUE TITLE
Deposition form - file upload failure 

### ISSUE THREAD

**Issue by edager** [Molecular-Biophysics-Database/mbdb-app#98]
Tester bugreport: 
After trying to upload a pdf file to the record at 09:25 (23-11-2023) then refreshing the entry view for the database I got the following error:

![image](https://github.com/Molecular-Biophysics-Database/mbdb-app/assets/20229814/d9eb72a0-885c-45b3-a2e4-57ab6d43c61a)

After removing the pdf file (it was only small, 189 kb) the entry page could be viewed again.

**Comment by MadCatX** [comment]
The actual error seems to be missing from the issue.

**Comment by edager** [comment]
My bad, sorry. I suspect a 500 error but I don't have access to the backend traceback

**Comment by edager** [comment]
I suspect this is caused not having a default value in case the description was not provided for files:

```jinja
{%- macro raw_measurements(raw_measurements, files) %} 

    {% for measurement_url in raw_measurements %}
        {% for file in files.entries %}
            {% if "files/" + file.key == measurement_url %}
                <a href="{{file.links.content}}" target="_blank">Download</a>
                Description:{{file.metadata.description.description}}
            {% endif %}
        {% endfor %}
    {% endfor %}
{% endmacro %}
```
link to offending code:

https://github.com/Molecular-Biophysics-Database/mbdb-app/blob/development/ui/mbdb-mst-ui/mbdb_mst_ui/templates/semantic-ui/mbdb_mst_ui/MBDB/RawMeasurements.jinja

**Comment by edager** [comment]
This should be fixed by the new jinjax template
